substitutions:
  name: esphome-web-e0c2e8
  friendly_name: loud-esp-mini

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  on_boot:
    priority: 800
    then:
    - media_player.volume_set:
        id: loudesp
        volume: 50%

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password
  ap:
    ssid: "$name Hotspot"
    password: !secret esphome_ap_password

psram:
  mode: octal
  speed: 80MHz

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26

media_player:
  - platform: i2s_audio
    name: $friendly_name
    id: loudesp
    dac_type: external
    i2s_dout_pin: GPIO22
    mode: stereo
    on_play: 
      then:
        - light.addressable_set: 
            id: rgb_light
            red: 0
            green: 50%
            blue: 0
    on_pause: 
      then:
        - light.addressable_set: 
            id: rgb_light
            red: 50%
            green: 0
            blue: 0    
            
light:
  - platform: esp32_rmt_led_strip
    id: rgb_light
    rgb_order: GRB
    pin: GPIO33
    num_leds: 1
    rmt_channel: 1
    chipset: ws2812
    name: "RGB led"